create table person
(
    id         integer generated by default as identity
        primary key,
    name       varchar(35) not null,
    surname    varchar(35) not null,
    last_name  varchar(35),
    birth_year integer
        constraint person_birth_year_check
            check ((birth_year >= 1900) AND ((birth_year)::numeric <= EXTRACT(year FROM CURRENT_DATE)))
);

create table book
(
    id              integer generated by default as identity
        primary key,
    title           varchar(75)  not null,
    author          varchar(100) not null,
    production_year integer      not null
        constraint book_production_year_check
            check ((production_year)::numeric <= EXTRACT(year FROM CURRENT_DATE)),
    person_id       integer
                                 references person
                                     on delete set null,
    taken_at        timestamp
);

-- Вставка данных в таблицу person
INSERT INTO person (name, surname, last_name, birth_year)
VALUES
('John', 'Doe', 'Edward', 1980),
('Jane', 'Smith', 'Alice', 1975),
('Michael', 'Johnson', 'David', 1990),
('Emily', 'Brown', 'Ann', 1985),
('Chris', 'Davis', 'James', 1978),
('Sarah', 'Miller', 'Marie', 1995),
('David', 'Wilson', 'Paul', 1965),
('Emma', 'Moore', 'Jane', 2000),
('Daniel', 'Taylor', 'Michael', 1988),
('Sophia', 'Anderson', 'Rose', 1992);

-- Вставка данных в таблицу book
INSERT INTO book (title, author, production_year, person_id, taken_at)
VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 1, '2024-01-15 10:00:00'),
('To Kill a Mockingbird', 'Harper Lee', 1960, 1, '2024-02-20 11:00:00'),
('1984', 'George Orwell', 1949, 2, '2024-03-10 14:00:00'),
('Pride and Prejudice', 'Jane Austen', 1813, 2, '2024-04-01 16:00:00'),
('The Catcher in the Rye', 'J.D. Salinger', 1951, 3, '2024-05-05 09:00:00'),
('Moby Dick', 'Herman Melville', 1851, NULL, NULL),
('War and Peace', 'Leo Tolstoy', 1869, 4, '2024-06-18 12:00:00'),
('The Odyssey', 'Homer', -800, 4, '2024-07-03 13:00:00'),
('Crime and Punishment', 'Fyodor Dostoevsky', 1866, NULL, NULL),
('Jane Eyre', 'Charlotte Bronte', 1847, 5, '2024-08-22 10:30:00'),
('Brave New World', 'Aldous Huxley', 1932, 6, '2024-09-15 11:45:00'),
('The Hobbit', 'J.R.R. Tolkien', 1937, 6, '2024-10-05 13:20:00'),
('The Iliad', 'Homer', -750, 7, '2024-11-10 08:15:00'),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880, NULL, NULL),
('The Divine Comedy', 'Dante Alighieri', 1320, 8, '2024-12-25 17:00:00'),
('Great Expectations', 'Charles Dickens', 1861, 9, '2025-01-05 19:30:00'),
('Ulysses', 'James Joyce', 1922, 9, '2025-02-14 21:45:00'),
('Anna Karenina', 'Leo Tolstoy', 1877, 10, '2025-03-22 11:00:00'),
('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967, NULL, NULL),
('Wuthering Heights', 'Emily Bronte', 1847, 10, '2025-04-11 15:30:00');